### ISSUE TITLE
Add GUI

### ISSUE THREAD

**Issue by dev-essbee** [dev-SB/iplt20-scrapper#2]
Add GUI, that will allow the user to select **year** and **type of stat** and then either display it in the interface or download the file or maybe both.  If you would like to work on the issue please comment below

**Comment by erfanhamdi** [comment]
Hey there @dev-SB I would like to work on it but had a question about whether you Want it to be done with a separate UI file designed with a qt designer or kind of embedded UI class ?

**Comment by dev-essbee** [comment]
I would prefer a separate UI file, also let's allow the user to go with terminal or GUI.

**Comment by dev-essbee** [comment]
Hey @JayJoeAy, are you working on the issue?

**Comment by erfanhamdi** [comment]
Sorry @dev-SB but I ran into some other projects and don't think I could get to work on it any time soon ..
